/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package camera_rent;

import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author M . FR
 */
public class Penyewaan extends javax.swing.JFrame {

    int jmlhari;

    /**
     * Creates new form Penyewaan
     */
    public Penyewaan() {
        initComponents();
        LoadData ld = new LoadData();
        ld.loadKeranjang(tb_keranjang);

        SubTotal st = new SubTotal();
        st.tambah(tb_keranjang, t_subtotal);
        
//        Total tot = new Total();
//        tot.akhir(tgl_kembali, tgl_pinjam, t_akhir, t_subtotal);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        t_akhir = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_keranjang = new javax.swing.JTable();
        tgl_pinjam = new com.toedter.calendar.JDateChooser();
        tgl_kembali = new com.toedter.calendar.JDateChooser();
        jButton2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        t_subtotal = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(860, 540));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Adobe Caslon Pro Bold", 0, 18)); // NOI18N
        jLabel1.setText("Data Pesanan :");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(70, 200, 130, 19);

        jLabel2.setFont(new java.awt.Font("Adobe Caslon Pro Bold", 0, 14)); // NOI18N
        jLabel2.setText("Lama Peminjaman :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(80, 400, 140, 20);

        jLabel3.setText("Hari Peminjaman");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(120, 430, 100, 14);

        jLabel4.setText("Hari Pengembalian");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(120, 470, 110, 14);

        jLabel5.setFont(new java.awt.Font("Adobe Caslon Pro Bold", 0, 12)); // NOI18N
        jLabel5.setText("Total");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(730, 400, 40, 20);

        t_akhir.setText("0");
        getContentPane().add(t_akhir);
        t_akhir.setBounds(720, 424, 90, 30);

        tb_keranjang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tb_keranjang);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(200, 200, 640, 190);
        getContentPane().add(tgl_pinjam);
        tgl_pinjam.setBounds(280, 420, 160, 30);
        getContentPane().add(tgl_kembali);
        tgl_kembali.setBounds(280, 460, 160, 30);

        jButton2.setText("Kembali");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(750, 460, 90, 30);

        jLabel7.setFont(new java.awt.Font("Adobe Caslon Pro Bold", 0, 12)); // NOI18N
        jLabel7.setText("SubTotal");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(600, 400, 60, 20);

        t_subtotal.setText("0");
        getContentPane().add(t_subtotal);
        t_subtotal.setBounds(590, 424, 80, 30);

        jButton1.setText("Selanjutnya");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(650, 460, 90, 30);

        jButton3.setText("Hitung");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(550, 460, 90, 30);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Dashboard da = new Dashboard();
        da.setVisible(true);
        da.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Datadiri dat = new Datadiri();
        dat.setVisible(true);
        dat.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        Date tglkembali = tgl_kembali.getDate();
        Date tglpinjam = tgl_pinjam.getDate();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyyMMdd");
        int pinjam1 = Integer.parseInt(sdf.format(tglpinjam));
        int kembali1 = Integer.parseInt(sdf.format(tglkembali));
        jmlhari = kembali1 - pinjam1;
        int sutot = Integer.parseInt(t_subtotal.getText());
        int hir = jmlhari * sutot;
        String akhir = String.valueOf(hir);
        JOptionPane.showMessageDialog(null,"SEWA" + jmlhari + " Hari");
        t_akhir.setText(akhir);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Penyewaan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Penyewaan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Penyewaan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Penyewaan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Penyewaan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel t_akhir;
    private javax.swing.JLabel t_subtotal;
    private javax.swing.JTable tb_keranjang;
    private com.toedter.calendar.JDateChooser tgl_kembali;
    private com.toedter.calendar.JDateChooser tgl_pinjam;
    // End of variables declaration//GEN-END:variables
}
