/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package camera_rent;

import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author M . FR
 */
public class Penyewaan extends javax.swing.JFrame {

    int jmlhari;

    /**
     * Creates new form Penyewaan
     */
    public Penyewaan() {
        initComponents();
        LoadData ld = new LoadData();
        ld.loadKeranjang(tb_keranjang);

        SubTotal st = new SubTotal();
        st.tambah(tb_keranjang, t_subtotal);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        t_akhir = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_keranjang = new javax.swing.JTable();
        tgl_pinjam = new com.toedter.calendar.JDateChooser();
        tgl_kembali = new com.toedter.calendar.JDateChooser();
        jButton2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        t_subtotal = new javax.swing.JLabel();
        btn_lanjut = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(860, 540));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Adobe Caslon Pro Bold", 0, 18)); // NOI18N
        jLabel1.setText("Data Pesanan :");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 130, 130, 24);

        jLabel2.setFont(new java.awt.Font("Adobe Caslon Pro Bold", 1, 14)); // NOI18N
        jLabel2.setText("Lama Peminjaman :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 330, 140, 20);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Hari Peminjaman");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(60, 350, 130, 40);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Hari Pengembalian");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(60, 400, 130, 50);

        jLabel5.setFont(new java.awt.Font("Adobe Caslon Pro Bold", 0, 12)); // NOI18N
        jLabel5.setText("Total");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(690, 340, 40, 20);

        t_akhir.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        t_akhir.setText("0");
        getContentPane().add(t_akhir);
        t_akhir.setBounds(680, 360, 100, 70);

        tb_keranjang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tb_keranjang);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(140, 130, 640, 190);
        getContentPane().add(tgl_pinjam);
        tgl_pinjam.setBounds(220, 350, 170, 40);

        tgl_kembali.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                tgl_kembaliPropertyChange(evt);
            }
        });
        getContentPane().add(tgl_kembali);
        tgl_kembali.setBounds(220, 410, 170, 40);

        jButton2.setText("Kembali");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(280, 460, 110, 30);

        jLabel7.setFont(new java.awt.Font("Adobe Caslon Pro Bold", 0, 12)); // NOI18N
        jLabel7.setText("SubTotal");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(560, 340, 60, 20);

        t_subtotal.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        t_subtotal.setText("0");
        getContentPane().add(t_subtotal);
        t_subtotal.setBounds(550, 360, 100, 70);

        btn_lanjut.setText("Selanjutnya");
        btn_lanjut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_lanjutActionPerformed(evt);
            }
        });
        getContentPane().add(btn_lanjut);
        btn_lanjut.setBounds(660, 460, 120, 30);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/penyewaan.png"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 0, 860, 540);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Dashboard da = new Dashboard();
        da.setVisible(true);
        da.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btn_lanjutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_lanjutActionPerformed
        // TODO add your handling code here:
        SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
        String pinjam = sdf.format(tgl_pinjam.getDate()).toString();
        String kembali = sdf.format(tgl_kembali.getDate()).toString();
        int row = tb_keranjang.getRowCount();
        List list = new ArrayList<>();
        List nama = new ArrayList<>();
        for (int i = 0; i < row; i++) {
            list.add(tb_keranjang.getValueAt(i, 0).toString());
            System.out.println(tb_keranjang.getValueAt(i, 0).toString());
            nama.add(tb_keranjang.getValueAt(i, 1).toString());
            System.out.println(tb_keranjang.getValueAt(i, 1).toString());
        }
        Total total = new Total();
        int tot = total.akhir(tgl_pinjam, tgl_kembali, t_akhir, t_subtotal);
        Datadiri dat = new Datadiri(row, list, nama, pinjam, kembali, tot);
        dat.setVisible(true);
        dat.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btn_lanjutActionPerformed

    private void tgl_kembaliPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_tgl_kembaliPropertyChange
        if (tgl_kembali.getDate() != null) {
            Total total = new Total();
            total.akhir(tgl_pinjam, tgl_kembali, t_akhir, t_subtotal);
            
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_tgl_kembaliPropertyChange

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Penyewaan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Penyewaan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Penyewaan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Penyewaan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Penyewaan().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_lanjut;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel t_akhir;
    private javax.swing.JLabel t_subtotal;
    private javax.swing.JTable tb_keranjang;
    private com.toedter.calendar.JDateChooser tgl_kembali;
    private com.toedter.calendar.JDateChooser tgl_pinjam;
    // End of variables declaration//GEN-END:variables
}
